### ISSUE TITLE
VIRUSTOTAL SCORE 16/69

### ISSUE THREAD

**Issue by xkorrupt** [AndrewDarkyy/Colorbot#4]
https://www.virustotal.com/gui/file/d428a3fdf037e55e53f09bcb35e128be4698d6be46cc36cef7ed6fea1a70c0e3/detection
![image](https://github.com/AndrewDarkyy/Colorbot-Modded/assets/134173277/8c029145-3e8d-49b9-99b9-e68ed5421a66)

**Comment by AndrewDarkyy** [comment]
these are false positives
